// AUTH
export const AUTH_REGISTER_USER = 'AUTH_REGISTER_USER';
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOG_OUT_USER = 'AUTH_LOG_OUT_USER';
export const AUTH_CHECK_WALLET = 'AUTH_CHECK_WALLET';

// APP
export const APP_COLLAPSED_SIDEBAR = 'APP_COLLAPSED_SIDEBAR';
